apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  labels:
    io.kompose.service: api
  name: api
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
